# Generated by Django 4.2.4 on 2023-10-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('close', 'Close'), ('waiting', 'Waiting')], default='waiting', max_length=20),
        ),
    ]
