# Generated by Django 4.2.4 on 2023-10-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('active', 'Active'), ('waiting', 'Waiting')], default='waiting', max_length=20),
        ),
    ]
