# Generated by Django 4.2.4 on 2023-10-27 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_city_district'),
        ('accounts', '0005_city_province_district_city_province_address'),
    ]

    operations = [
    ]
