# Generated by Django 4.2.4 on 2023-11-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20231027_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='area',
            field=models.CharField(choices=[('Kota', 'Kota'), ('Kabupaten', 'Kabupaten')], default='Kota', max_length=10),
        ),
    ]
