# Generated by Django 4.2.4 on 2023-11-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_city_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='area',
            field=models.CharField(choices=[('Kabupaten', 'Kabupaten'), ('Kota', 'Kota')], default='Kota', max_length=10),
        ),
    ]
