# Generated by Django 4.2.4 on 2023-12-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_city_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='area',
            field=models.CharField(choices=[('Kota', 'Kota'), ('Kabupaten', 'Kabupaten')], default='Kota', max_length=10),
        ),
    ]
