# Generated by Django 4.1.5 on 2023-03-17 03:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
