# Generated by Django 4.2.4 on 2023-09-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_long_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPaket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_weight', models.CharField(blank=True, max_length=150)),
                ('length', models.CharField(blank=True, max_length=150)),
                ('width', models.CharField(blank=True, max_length=150)),
                ('height', models.CharField(blank=True, max_length=150)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Product Paket',
                'verbose_name_plural': 'Product Paket',
            },
        ),
    ]
