# Generated by Django 4.2.4 on 2023-09-28 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_productpaket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users_wislist',
            field=models.ManyToManyField(blank=True, related_name='user_wislish', to=settings.AUTH_USER_MODEL),
        ),
    ]
