# Generated by Django 4.2.4 on 2023-11-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_users_wislist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpaket',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='productpaket',
            name='length',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='productpaket',
            name='max_weight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='productpaket',
            name='width',
            field=models.IntegerField(blank=True),
        ),
    ]
