# Generated by Django 4.2.4 on 2023-11-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productpaket_height_alter_productpaket_length_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpaket',
            old_name='max_weight',
            new_name='weight',
        ),
    ]
