# Generated by Django 4.1.5 on 2023-03-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product Gallery', 'verbose_name_plural': 'product Gallery'},
        ),
    ]
