# Generated by Django 4.2.4 on 2023-12-29 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewcount',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='product_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
