# Generated by Django 4.2.4 on 2023-12-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_viewcount_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewcount',
            name='likes',
        ),
    ]
