# Generated by Django 4.2.4 on 2023-11-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_city_remove_order_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('NEW', 'NEW'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='NEW', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.FloatField(blank=True),
        ),
    ]
