# Generated by Django 4.2.4 on 2023-11-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status_orderdelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED'), ('ACCEPTED', 'ACCEPTED'), ('NEW', 'NEW')], default='NEW', max_length=10),
        ),
    ]
