# Generated by Django 4.2.4 on 2023-12-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('NEW', 'NEW'), ('COMPLETED', 'COMPLETED'), ('ACCEPTED', 'ACCEPTED')], default='NEW', max_length=10),
        ),
    ]
