# Generated by Django 4.2.4 on 2023-09-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('CANCELLED', 'CANCELLED'), ('ACCEPTED', 'ACCEPTED'), ('COMPLETED', 'COMPLETED')], default='NEW', max_length=10),
        ),
    ]
