# Generated by Django 4.2.4 on 2023-10-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('COMPLETED', 'COMPLETED'), ('ACCEPTED', 'ACCEPTED'), ('NEW', 'NEW')], default='NEW', max_length=10),
        ),
    ]
