# Generated by Django 4.2.4 on 2023-12-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('ACCEPTED', 'ACCEPTED'), ('NEW', 'NEW'), ('COMPLETED', 'COMPLETED')], default='NEW', max_length=10),
        ),
    ]
