# Generated by Django 4.2.4 on 2023-10-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('NEW', 'NEW'), ('ACCEPTED', 'ACCEPTED')], default='NEW', max_length=10),
        ),
    ]
