# Generated by Django 4.2.4 on 2023-11-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACCEPTED', 'ACCEPTED'), ('CANCELLED', 'CANCELLED'), ('NEW', 'NEW'), ('COMPLETED', 'COMPLETED')], default='NEW', max_length=10),
        ),
    ]
